export default [
  {
    id: 1,
    personImg: "../images/bale.jpg",
    starImg: "../images/redstar.png",
    rated: "3.9",
    num_rated: "06",
    nationality: "WALES",
    charge: "545",
    quote: "Sometimes in life, just forget about your worries and have some fun",
  },
  {
    id: 2,
    personImg: "../images/gerard.jpg",
    starImg: "../images/redstar.png",
    rated: "4.5",
    num_rated: "106",
    nationality: "ENGLAND",
    charge: "745",
    quote: "Life never gets easier, just keep going",
  },
  {
    id: 3,
    personImg: "../images/hazard.png",
    starImg: "../images/redstar.png",
    rated: "4.1",
    num_rated: "90",
    nationality: "BELGIUM",
    charge: "445",
    quote: "One wrong decison can spoil your whole career",
  },
  {
    id: 4,
    personImg: "../images/ronaldo.png",
    starImg: "../images/redstar.png",
    rated: "4.9",
    num_rated: "1000",
    nationality: "PORTUGAL",
    charge: "1945",
    quote: "Sometimes hardwork is all you need to succeed",
  },
  
  {
    id: 5,
    personImg: "../images/mata.jpg",
    starImg: "../images/redstar.png",
    rated: "4.4",
    num_rated: "299",
    nationality: "SPAIN",
    charge: "945",
    quote: "Old wine never loses it's taste, just gets better in taste",
  },
  {
    id: 6,
    personImg: "../images/mbape.jpg",
    starImg: "../images/redstar.png",
    rated: "4.6",
    num_rated: "667",
    nationality: "FRANCE",
    charge: "945",
    quote: "Grind hard in your young age, dont relent and be humble",
  },
  {
    id: 7,
    personImg: "../images/neymar.jpg",
    starImg: "../images/redstar.png",
    rated: "4.0",
    num_rated: "236",
    nationality: "BRAZIL",
    charge: "345",
    quote: "is good to make your own name but also better to have a master",
  },
  {
    id: 8,
    personImg: "../images/neuer.jpg",
    starImg: "../images/redstar.png",
    rated: "4.7",
    num_rated: "776",
    nationality: "GERMANY",
    charge: "545",
    quote: "Keep going till your body calls it quit.",
  },
  {
    id: 9,
    personImg: "../images/rashford.jpg",
    starImg: "../images/redstar.png",
    rated: "3.8",
    num_rated: "106",
    nationality: "ENGLAND",
    charge: "245",
    quote: "A little help rendered to the needy impact your personality",
  },
  {
    id: 10,
    personImg: "../images/robben.png",
    starImg: "../images/redstar.png",
    rated: "4.2",
    num_rated: "106",
    nationality: "NETHERLAND",
    charge: "945",
    quote: "Quitters never win, keep it going",
  },
  {
    id: 11,
    personImg: "../images/messi.jpg",
    starImg: "../images/redstar.png",
    rated: "4.9",
    num_rated: "1000",
    nationality: "ARGENTINA",
    charge: "1945",
    quote: "Gift from above is supernatural, then adding hardwork is everything",
  },
  {
    id: 12,
    personImg: "../images/rooney.jpg",
    starImg: "../images/redstar.png",
    rated: "4.8",
    num_rated: "1106",
    nationality: "ENGLAND",
    charge: "845",
    quote: "Practise makes perfect,just be a team player and flourish",
  },
];
